name: Lint and Prettier

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: "18.x"

jobs:
  run-lint-and-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Prettier
        run: npm run prettier
